### ISSUE TITLE
Manga.IntegrationTests.CustomerRegistration.Register_Deposit_Withdraw_Close test fails lacking dependencies

### ISSUE THREAD

**Issue by morphlogic** [ivanpaulovich/clean-architecture-manga#22]
Running Manga.IntegrationTests.CustomerRegistration.Register_Deposit_Withdraw_Closefails with the following stack trace:

System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore.Mvc, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Stack Trace:
   at Manga.WebApi.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Manga.IntegrationTests.CustomerRegistration..ctor() in C:\dev\code\clean-architecture-manga\manga\test\Manga.WebApi.Tests\CustomerRegistration.cs:line 33

**Comment by morphlogic** [comment]
Resolved with PR #23 - thank you, @ivanpaulovich !
